// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 31.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `attestation.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:attestation.HelloRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct HelloRequest {
    // message fields
    // @@protoc_insertion_point(field:attestation.HelloRequest.version)
    pub version: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:attestation.HelloRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a HelloRequest {
    fn default() -> &'a HelloRequest {
        <HelloRequest as ::protobuf::Message>::default_instance()
    }
}

impl HelloRequest {
    pub fn new() -> HelloRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "version",
            |m: &HelloRequest| { &m.version },
            |m: &mut HelloRequest| { &mut m.version },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<HelloRequest>(
            "HelloRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for HelloRequest {
    const NAME: &'static str = "HelloRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.version = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.version.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.version);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.version.is_empty() {
            os.write_string(1, &self.version)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> HelloRequest {
        HelloRequest::new()
    }

    fn clear(&mut self) {
        self.version.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static HelloRequest {
        static instance: HelloRequest = HelloRequest {
            version: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for HelloRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("HelloRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for HelloRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for HelloRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:attestation.HelloResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct HelloResponse {
    // message fields
    // @@protoc_insertion_point(field:attestation.HelloResponse.error_code)
    pub error_code: ::protobuf::EnumOrUnknown<ErrorCode>,
    // @@protoc_insertion_point(field:attestation.HelloResponse.tee)
    pub tee: ::protobuf::EnumOrUnknown<TEE>,
    // @@protoc_insertion_point(field:attestation.HelloResponse.mode)
    pub mode: ::protobuf::EnumOrUnknown<Mode>,
    // special fields
    // @@protoc_insertion_point(special_field:attestation.HelloResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a HelloResponse {
    fn default() -> &'a HelloResponse {
        <HelloResponse as ::protobuf::Message>::default_instance()
    }
}

impl HelloResponse {
    pub fn new() -> HelloResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "error_code",
            |m: &HelloResponse| { &m.error_code },
            |m: &mut HelloResponse| { &mut m.error_code },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "tee",
            |m: &HelloResponse| { &m.tee },
            |m: &mut HelloResponse| { &mut m.tee },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "mode",
            |m: &HelloResponse| { &m.mode },
            |m: &mut HelloResponse| { &mut m.mode },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<HelloResponse>(
            "HelloResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for HelloResponse {
    const NAME: &'static str = "HelloResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.error_code = is.read_enum_or_unknown()?;
                },
                16 => {
                    self.tee = is.read_enum_or_unknown()?;
                },
                24 => {
                    self.mode = is.read_enum_or_unknown()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.error_code != ::protobuf::EnumOrUnknown::new(ErrorCode::ErrorCode_OK) {
            my_size += ::protobuf::rt::int32_size(1, self.error_code.value());
        }
        if self.tee != ::protobuf::EnumOrUnknown::new(TEE::TEE_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(2, self.tee.value());
        }
        if self.mode != ::protobuf::EnumOrUnknown::new(Mode::MODE_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(3, self.mode.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.error_code != ::protobuf::EnumOrUnknown::new(ErrorCode::ErrorCode_OK) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.error_code))?;
        }
        if self.tee != ::protobuf::EnumOrUnknown::new(TEE::TEE_UNSPECIFIED) {
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(&self.tee))?;
        }
        if self.mode != ::protobuf::EnumOrUnknown::new(Mode::MODE_UNSPECIFIED) {
            os.write_enum(3, ::protobuf::EnumOrUnknown::value(&self.mode))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> HelloResponse {
        HelloResponse::new()
    }

    fn clear(&mut self) {
        self.error_code = ::protobuf::EnumOrUnknown::new(ErrorCode::ErrorCode_OK);
        self.tee = ::protobuf::EnumOrUnknown::new(TEE::TEE_UNSPECIFIED);
        self.mode = ::protobuf::EnumOrUnknown::new(Mode::MODE_UNSPECIFIED);
        self.special_fields.clear();
    }

    fn default_instance() -> &'static HelloResponse {
        static instance: HelloResponse = HelloResponse {
            error_code: ::protobuf::EnumOrUnknown::from_i32(0),
            tee: ::protobuf::EnumOrUnknown::from_i32(0),
            mode: ::protobuf::EnumOrUnknown::from_i32(0),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for HelloResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("HelloResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for HelloResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for HelloResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:attestation.Evidence)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Evidence {
    // message fields
    // @@protoc_insertion_point(field:attestation.Evidence.init_data)
    pub init_data: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:attestation.Evidence.runtime_data)
    pub runtime_data: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:attestation.Evidence.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Evidence {
    fn default() -> &'a Evidence {
        <Evidence as ::protobuf::Message>::default_instance()
    }
}

impl Evidence {
    pub fn new() -> Evidence {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "init_data",
            |m: &Evidence| { &m.init_data },
            |m: &mut Evidence| { &mut m.init_data },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "runtime_data",
            |m: &Evidence| { &m.runtime_data },
            |m: &mut Evidence| { &mut m.runtime_data },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Evidence>(
            "Evidence",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Evidence {
    const NAME: &'static str = "Evidence";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.init_data = is.read_bytes()?;
                },
                18 => {
                    self.runtime_data = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.init_data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.init_data);
        }
        if !self.runtime_data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.runtime_data);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.init_data.is_empty() {
            os.write_bytes(1, &self.init_data)?;
        }
        if !self.runtime_data.is_empty() {
            os.write_bytes(2, &self.runtime_data)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Evidence {
        Evidence::new()
    }

    fn clear(&mut self) {
        self.init_data.clear();
        self.runtime_data.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Evidence {
        static instance: Evidence = Evidence {
            init_data: ::std::vec::Vec::new(),
            runtime_data: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Evidence {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Evidence").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Evidence {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Evidence {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:attestation.EvidenceList)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct EvidenceList {
    // message fields
    // @@protoc_insertion_point(field:attestation.EvidenceList.evidence)
    pub evidence: ::std::vec::Vec<Evidence>,
    // special fields
    // @@protoc_insertion_point(special_field:attestation.EvidenceList.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a EvidenceList {
    fn default() -> &'a EvidenceList {
        <EvidenceList as ::protobuf::Message>::default_instance()
    }
}

impl EvidenceList {
    pub fn new() -> EvidenceList {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "evidence",
            |m: &EvidenceList| { &m.evidence },
            |m: &mut EvidenceList| { &mut m.evidence },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<EvidenceList>(
            "EvidenceList",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for EvidenceList {
    const NAME: &'static str = "EvidenceList";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.evidence.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.evidence {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.evidence {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> EvidenceList {
        EvidenceList::new()
    }

    fn clear(&mut self) {
        self.evidence.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static EvidenceList {
        static instance: EvidenceList = EvidenceList {
            evidence: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for EvidenceList {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("EvidenceList").unwrap()).clone()
    }
}

impl ::std::fmt::Display for EvidenceList {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for EvidenceList {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:attestation.AttestationRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct AttestationRequest {
    // message fields
    // @@protoc_insertion_point(field:attestation.AttestationRequest.mode)
    pub mode: ::protobuf::EnumOrUnknown<Mode>,
    // @@protoc_insertion_point(field:attestation.AttestationRequest.nonce)
    pub nonce: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:attestation.AttestationRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a AttestationRequest {
    fn default() -> &'a AttestationRequest {
        <AttestationRequest as ::protobuf::Message>::default_instance()
    }
}

impl AttestationRequest {
    pub fn new() -> AttestationRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "mode",
            |m: &AttestationRequest| { &m.mode },
            |m: &mut AttestationRequest| { &mut m.mode },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "nonce",
            |m: &AttestationRequest| { &m.nonce },
            |m: &mut AttestationRequest| { &mut m.nonce },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<AttestationRequest>(
            "AttestationRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for AttestationRequest {
    const NAME: &'static str = "AttestationRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.mode = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.nonce = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.mode != ::protobuf::EnumOrUnknown::new(Mode::MODE_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(1, self.mode.value());
        }
        if !self.nonce.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.nonce);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.mode != ::protobuf::EnumOrUnknown::new(Mode::MODE_UNSPECIFIED) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.mode))?;
        }
        if !self.nonce.is_empty() {
            os.write_bytes(2, &self.nonce)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> AttestationRequest {
        AttestationRequest::new()
    }

    fn clear(&mut self) {
        self.mode = ::protobuf::EnumOrUnknown::new(Mode::MODE_UNSPECIFIED);
        self.nonce.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static AttestationRequest {
        static instance: AttestationRequest = AttestationRequest {
            mode: ::protobuf::EnumOrUnknown::from_i32(0),
            nonce: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for AttestationRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("AttestationRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for AttestationRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AttestationRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:attestation.AttestationResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct AttestationResponse {
    // message fields
    // @@protoc_insertion_point(field:attestation.AttestationResponse.error_code)
    pub error_code: ::protobuf::EnumOrUnknown<ErrorCode>,
    // message oneof groups
    pub result: ::std::option::Option<attestation_response::Result>,
    // special fields
    // @@protoc_insertion_point(special_field:attestation.AttestationResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a AttestationResponse {
    fn default() -> &'a AttestationResponse {
        <AttestationResponse as ::protobuf::Message>::default_instance()
    }
}

impl AttestationResponse {
    pub fn new() -> AttestationResponse {
        ::std::default::Default::default()
    }

    // .attestation.EvidenceList evidence_list = 2;

    pub fn evidence_list(&self) -> &EvidenceList {
        match self.result {
            ::std::option::Option::Some(attestation_response::Result::EvidenceList(ref v)) => v,
            _ => <EvidenceList as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_evidence_list(&mut self) {
        self.result = ::std::option::Option::None;
    }

    pub fn has_evidence_list(&self) -> bool {
        match self.result {
            ::std::option::Option::Some(attestation_response::Result::EvidenceList(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_evidence_list(&mut self, v: EvidenceList) {
        self.result = ::std::option::Option::Some(attestation_response::Result::EvidenceList(v))
    }

    // Mutable pointer to the field.
    pub fn mut_evidence_list(&mut self) -> &mut EvidenceList {
        if let ::std::option::Option::Some(attestation_response::Result::EvidenceList(_)) = self.result {
        } else {
            self.result = ::std::option::Option::Some(attestation_response::Result::EvidenceList(EvidenceList::new()));
        }
        match self.result {
            ::std::option::Option::Some(attestation_response::Result::EvidenceList(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_evidence_list(&mut self) -> EvidenceList {
        if self.has_evidence_list() {
            match self.result.take() {
                ::std::option::Option::Some(attestation_response::Result::EvidenceList(v)) => v,
                _ => panic!(),
            }
        } else {
            EvidenceList::new()
        }
    }

    // bytes attestation_token = 3;

    pub fn attestation_token(&self) -> &[u8] {
        match self.result {
            ::std::option::Option::Some(attestation_response::Result::AttestationToken(ref v)) => v,
            _ => &[],
        }
    }

    pub fn clear_attestation_token(&mut self) {
        self.result = ::std::option::Option::None;
    }

    pub fn has_attestation_token(&self) -> bool {
        match self.result {
            ::std::option::Option::Some(attestation_response::Result::AttestationToken(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_attestation_token(&mut self, v: ::std::vec::Vec<u8>) {
        self.result = ::std::option::Option::Some(attestation_response::Result::AttestationToken(v))
    }

    // Mutable pointer to the field.
    pub fn mut_attestation_token(&mut self) -> &mut ::std::vec::Vec<u8> {
        if let ::std::option::Option::Some(attestation_response::Result::AttestationToken(_)) = self.result {
        } else {
            self.result = ::std::option::Option::Some(attestation_response::Result::AttestationToken(::std::vec::Vec::new()));
        }
        match self.result {
            ::std::option::Option::Some(attestation_response::Result::AttestationToken(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_attestation_token(&mut self) -> ::std::vec::Vec<u8> {
        if self.has_attestation_token() {
            match self.result.take() {
                ::std::option::Option::Some(attestation_response::Result::AttestationToken(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::vec::Vec::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "error_code",
            |m: &AttestationResponse| { &m.error_code },
            |m: &mut AttestationResponse| { &mut m.error_code },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, EvidenceList>(
            "evidence_list",
            AttestationResponse::has_evidence_list,
            AttestationResponse::evidence_list,
            AttestationResponse::mut_evidence_list,
            AttestationResponse::set_evidence_list,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_deref_has_get_set_simpler_accessor::<_, _>(
            "attestation_token",
            AttestationResponse::has_attestation_token,
            AttestationResponse::attestation_token,
            AttestationResponse::set_attestation_token,
        ));
        oneofs.push(attestation_response::Result::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<AttestationResponse>(
            "AttestationResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for AttestationResponse {
    const NAME: &'static str = "AttestationResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.error_code = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.result = ::std::option::Option::Some(attestation_response::Result::EvidenceList(is.read_message()?));
                },
                26 => {
                    self.result = ::std::option::Option::Some(attestation_response::Result::AttestationToken(is.read_bytes()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.error_code != ::protobuf::EnumOrUnknown::new(ErrorCode::ErrorCode_OK) {
            my_size += ::protobuf::rt::int32_size(1, self.error_code.value());
        }
        if let ::std::option::Option::Some(ref v) = self.result {
            match v {
                &attestation_response::Result::EvidenceList(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &attestation_response::Result::AttestationToken(ref v) => {
                    my_size += ::protobuf::rt::bytes_size(3, &v);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.error_code != ::protobuf::EnumOrUnknown::new(ErrorCode::ErrorCode_OK) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.error_code))?;
        }
        if let ::std::option::Option::Some(ref v) = self.result {
            match v {
                &attestation_response::Result::EvidenceList(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
                },
                &attestation_response::Result::AttestationToken(ref v) => {
                    os.write_bytes(3, v)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> AttestationResponse {
        AttestationResponse::new()
    }

    fn clear(&mut self) {
        self.error_code = ::protobuf::EnumOrUnknown::new(ErrorCode::ErrorCode_OK);
        self.result = ::std::option::Option::None;
        self.result = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static AttestationResponse {
        static instance: AttestationResponse = AttestationResponse {
            error_code: ::protobuf::EnumOrUnknown::from_i32(0),
            result: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for AttestationResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("AttestationResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for AttestationResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AttestationResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `AttestationResponse`
pub mod attestation_response {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:attestation.AttestationResponse.result)
    pub enum Result {
        // @@protoc_insertion_point(oneof_field:attestation.AttestationResponse.evidence_list)
        EvidenceList(super::EvidenceList),
        // @@protoc_insertion_point(oneof_field:attestation.AttestationResponse.attestation_token)
        AttestationToken(::std::vec::Vec<u8>),
    }

    impl ::protobuf::Oneof for Result {
    }

    impl ::protobuf::OneofFull for Result {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::AttestationResponse as ::protobuf::MessageFull>::descriptor().oneof_by_name("result").unwrap()).clone()
        }
    }

    impl Result {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Result>("result")
        }
    }
}

// @@protoc_insertion_point(message:attestation.VerificationRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct VerificationRequest {
    // message fields
    // @@protoc_insertion_point(field:attestation.VerificationRequest.evidence)
    pub evidence: ::std::vec::Vec<Evidence>,
    // special fields
    // @@protoc_insertion_point(special_field:attestation.VerificationRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a VerificationRequest {
    fn default() -> &'a VerificationRequest {
        <VerificationRequest as ::protobuf::Message>::default_instance()
    }
}

impl VerificationRequest {
    pub fn new() -> VerificationRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "evidence",
            |m: &VerificationRequest| { &m.evidence },
            |m: &mut VerificationRequest| { &mut m.evidence },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<VerificationRequest>(
            "VerificationRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for VerificationRequest {
    const NAME: &'static str = "VerificationRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.evidence.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.evidence {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.evidence {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> VerificationRequest {
        VerificationRequest::new()
    }

    fn clear(&mut self) {
        self.evidence.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static VerificationRequest {
        static instance: VerificationRequest = VerificationRequest {
            evidence: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for VerificationRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("VerificationRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for VerificationRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for VerificationRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:attestation.VerificationResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct VerificationResponse {
    // message fields
    // @@protoc_insertion_point(field:attestation.VerificationResponse.error_code)
    pub error_code: ::protobuf::EnumOrUnknown<ErrorCode>,
    // @@protoc_insertion_point(field:attestation.VerificationResponse.attestation_token)
    pub attestation_token: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:attestation.VerificationResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a VerificationResponse {
    fn default() -> &'a VerificationResponse {
        <VerificationResponse as ::protobuf::Message>::default_instance()
    }
}

impl VerificationResponse {
    pub fn new() -> VerificationResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "error_code",
            |m: &VerificationResponse| { &m.error_code },
            |m: &mut VerificationResponse| { &mut m.error_code },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "attestation_token",
            |m: &VerificationResponse| { &m.attestation_token },
            |m: &mut VerificationResponse| { &mut m.attestation_token },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<VerificationResponse>(
            "VerificationResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for VerificationResponse {
    const NAME: &'static str = "VerificationResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.error_code = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.attestation_token = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.error_code != ::protobuf::EnumOrUnknown::new(ErrorCode::ErrorCode_OK) {
            my_size += ::protobuf::rt::int32_size(1, self.error_code.value());
        }
        if !self.attestation_token.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.attestation_token);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.error_code != ::protobuf::EnumOrUnknown::new(ErrorCode::ErrorCode_OK) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.error_code))?;
        }
        if !self.attestation_token.is_empty() {
            os.write_bytes(2, &self.attestation_token)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> VerificationResponse {
        VerificationResponse::new()
    }

    fn clear(&mut self) {
        self.error_code = ::protobuf::EnumOrUnknown::new(ErrorCode::ErrorCode_OK);
        self.attestation_token.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static VerificationResponse {
        static instance: VerificationResponse = VerificationResponse {
            error_code: ::protobuf::EnumOrUnknown::from_i32(0),
            attestation_token: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for VerificationResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("VerificationResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for VerificationResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for VerificationResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:attestation.RelyingPartyResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RelyingPartyResponse {
    // message fields
    // @@protoc_insertion_point(field:attestation.RelyingPartyResponse.error_code)
    pub error_code: ::protobuf::EnumOrUnknown<ErrorCode>,
    // @@protoc_insertion_point(field:attestation.RelyingPartyResponse.attestation_token)
    pub attestation_token: ::std::option::Option<::std::vec::Vec<u8>>,
    // special fields
    // @@protoc_insertion_point(special_field:attestation.RelyingPartyResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RelyingPartyResponse {
    fn default() -> &'a RelyingPartyResponse {
        <RelyingPartyResponse as ::protobuf::Message>::default_instance()
    }
}

impl RelyingPartyResponse {
    pub fn new() -> RelyingPartyResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "error_code",
            |m: &RelyingPartyResponse| { &m.error_code },
            |m: &mut RelyingPartyResponse| { &mut m.error_code },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "attestation_token",
            |m: &RelyingPartyResponse| { &m.attestation_token },
            |m: &mut RelyingPartyResponse| { &mut m.attestation_token },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RelyingPartyResponse>(
            "RelyingPartyResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RelyingPartyResponse {
    const NAME: &'static str = "RelyingPartyResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.error_code = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.attestation_token = ::std::option::Option::Some(is.read_bytes()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.error_code != ::protobuf::EnumOrUnknown::new(ErrorCode::ErrorCode_OK) {
            my_size += ::protobuf::rt::int32_size(1, self.error_code.value());
        }
        if let Some(v) = self.attestation_token.as_ref() {
            my_size += ::protobuf::rt::bytes_size(2, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.error_code != ::protobuf::EnumOrUnknown::new(ErrorCode::ErrorCode_OK) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.error_code))?;
        }
        if let Some(v) = self.attestation_token.as_ref() {
            os.write_bytes(2, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RelyingPartyResponse {
        RelyingPartyResponse::new()
    }

    fn clear(&mut self) {
        self.error_code = ::protobuf::EnumOrUnknown::new(ErrorCode::ErrorCode_OK);
        self.attestation_token = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RelyingPartyResponse {
        static instance: RelyingPartyResponse = RelyingPartyResponse {
            error_code: ::protobuf::EnumOrUnknown::from_i32(0),
            attestation_token: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RelyingPartyResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RelyingPartyResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RelyingPartyResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RelyingPartyResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:attestation.RpcRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RpcRequest {
    // message fields
    // @@protoc_insertion_point(field:attestation.RpcRequest.method)
    pub method: ::protobuf::EnumOrUnknown<RpcMethod>,
    // message oneof groups
    pub payload: ::std::option::Option<rpc_request::Payload>,
    // special fields
    // @@protoc_insertion_point(special_field:attestation.RpcRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RpcRequest {
    fn default() -> &'a RpcRequest {
        <RpcRequest as ::protobuf::Message>::default_instance()
    }
}

impl RpcRequest {
    pub fn new() -> RpcRequest {
        ::std::default::Default::default()
    }

    // .attestation.AttestationRequest attestation_request = 2;

    pub fn attestation_request(&self) -> &AttestationRequest {
        match self.payload {
            ::std::option::Option::Some(rpc_request::Payload::AttestationRequest(ref v)) => v,
            _ => <AttestationRequest as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_attestation_request(&mut self) {
        self.payload = ::std::option::Option::None;
    }

    pub fn has_attestation_request(&self) -> bool {
        match self.payload {
            ::std::option::Option::Some(rpc_request::Payload::AttestationRequest(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_attestation_request(&mut self, v: AttestationRequest) {
        self.payload = ::std::option::Option::Some(rpc_request::Payload::AttestationRequest(v))
    }

    // Mutable pointer to the field.
    pub fn mut_attestation_request(&mut self) -> &mut AttestationRequest {
        if let ::std::option::Option::Some(rpc_request::Payload::AttestationRequest(_)) = self.payload {
        } else {
            self.payload = ::std::option::Option::Some(rpc_request::Payload::AttestationRequest(AttestationRequest::new()));
        }
        match self.payload {
            ::std::option::Option::Some(rpc_request::Payload::AttestationRequest(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_attestation_request(&mut self) -> AttestationRequest {
        if self.has_attestation_request() {
            match self.payload.take() {
                ::std::option::Option::Some(rpc_request::Payload::AttestationRequest(v)) => v,
                _ => panic!(),
            }
        } else {
            AttestationRequest::new()
        }
    }

    // .attestation.VerificationRequest verification_request = 3;

    pub fn verification_request(&self) -> &VerificationRequest {
        match self.payload {
            ::std::option::Option::Some(rpc_request::Payload::VerificationRequest(ref v)) => v,
            _ => <VerificationRequest as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_verification_request(&mut self) {
        self.payload = ::std::option::Option::None;
    }

    pub fn has_verification_request(&self) -> bool {
        match self.payload {
            ::std::option::Option::Some(rpc_request::Payload::VerificationRequest(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_verification_request(&mut self, v: VerificationRequest) {
        self.payload = ::std::option::Option::Some(rpc_request::Payload::VerificationRequest(v))
    }

    // Mutable pointer to the field.
    pub fn mut_verification_request(&mut self) -> &mut VerificationRequest {
        if let ::std::option::Option::Some(rpc_request::Payload::VerificationRequest(_)) = self.payload {
        } else {
            self.payload = ::std::option::Option::Some(rpc_request::Payload::VerificationRequest(VerificationRequest::new()));
        }
        match self.payload {
            ::std::option::Option::Some(rpc_request::Payload::VerificationRequest(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_verification_request(&mut self) -> VerificationRequest {
        if self.has_verification_request() {
            match self.payload.take() {
                ::std::option::Option::Some(rpc_request::Payload::VerificationRequest(v)) => v,
                _ => panic!(),
            }
        } else {
            VerificationRequest::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "method",
            |m: &RpcRequest| { &m.method },
            |m: &mut RpcRequest| { &mut m.method },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, AttestationRequest>(
            "attestation_request",
            RpcRequest::has_attestation_request,
            RpcRequest::attestation_request,
            RpcRequest::mut_attestation_request,
            RpcRequest::set_attestation_request,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, VerificationRequest>(
            "verification_request",
            RpcRequest::has_verification_request,
            RpcRequest::verification_request,
            RpcRequest::mut_verification_request,
            RpcRequest::set_verification_request,
        ));
        oneofs.push(rpc_request::Payload::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RpcRequest>(
            "RpcRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RpcRequest {
    const NAME: &'static str = "RpcRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.method = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.payload = ::std::option::Option::Some(rpc_request::Payload::AttestationRequest(is.read_message()?));
                },
                26 => {
                    self.payload = ::std::option::Option::Some(rpc_request::Payload::VerificationRequest(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.method != ::protobuf::EnumOrUnknown::new(RpcMethod::RPC_METHOD_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(1, self.method.value());
        }
        if let ::std::option::Option::Some(ref v) = self.payload {
            match v {
                &rpc_request::Payload::AttestationRequest(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &rpc_request::Payload::VerificationRequest(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.method != ::protobuf::EnumOrUnknown::new(RpcMethod::RPC_METHOD_UNSPECIFIED) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.method))?;
        }
        if let ::std::option::Option::Some(ref v) = self.payload {
            match v {
                &rpc_request::Payload::AttestationRequest(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
                },
                &rpc_request::Payload::VerificationRequest(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RpcRequest {
        RpcRequest::new()
    }

    fn clear(&mut self) {
        self.method = ::protobuf::EnumOrUnknown::new(RpcMethod::RPC_METHOD_UNSPECIFIED);
        self.payload = ::std::option::Option::None;
        self.payload = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RpcRequest {
        static instance: RpcRequest = RpcRequest {
            method: ::protobuf::EnumOrUnknown::from_i32(0),
            payload: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RpcRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RpcRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RpcRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RpcRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `RpcRequest`
pub mod rpc_request {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:attestation.RpcRequest.payload)
    pub enum Payload {
        // @@protoc_insertion_point(oneof_field:attestation.RpcRequest.attestation_request)
        AttestationRequest(super::AttestationRequest),
        // @@protoc_insertion_point(oneof_field:attestation.RpcRequest.verification_request)
        VerificationRequest(super::VerificationRequest),
    }

    impl ::protobuf::Oneof for Payload {
    }

    impl ::protobuf::OneofFull for Payload {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::RpcRequest as ::protobuf::MessageFull>::descriptor().oneof_by_name("payload").unwrap()).clone()
        }
    }

    impl Payload {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Payload>("payload")
        }
    }
}

// @@protoc_insertion_point(message:attestation.RpcResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RpcResponse {
    // message fields
    // @@protoc_insertion_point(field:attestation.RpcResponse.method)
    pub method: ::protobuf::EnumOrUnknown<RpcMethod>,
    // message oneof groups
    pub payload: ::std::option::Option<rpc_response::Payload>,
    // special fields
    // @@protoc_insertion_point(special_field:attestation.RpcResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RpcResponse {
    fn default() -> &'a RpcResponse {
        <RpcResponse as ::protobuf::Message>::default_instance()
    }
}

impl RpcResponse {
    pub fn new() -> RpcResponse {
        ::std::default::Default::default()
    }

    // .attestation.AttestationResponse attestation_response = 2;

    pub fn attestation_response(&self) -> &AttestationResponse {
        match self.payload {
            ::std::option::Option::Some(rpc_response::Payload::AttestationResponse(ref v)) => v,
            _ => <AttestationResponse as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_attestation_response(&mut self) {
        self.payload = ::std::option::Option::None;
    }

    pub fn has_attestation_response(&self) -> bool {
        match self.payload {
            ::std::option::Option::Some(rpc_response::Payload::AttestationResponse(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_attestation_response(&mut self, v: AttestationResponse) {
        self.payload = ::std::option::Option::Some(rpc_response::Payload::AttestationResponse(v))
    }

    // Mutable pointer to the field.
    pub fn mut_attestation_response(&mut self) -> &mut AttestationResponse {
        if let ::std::option::Option::Some(rpc_response::Payload::AttestationResponse(_)) = self.payload {
        } else {
            self.payload = ::std::option::Option::Some(rpc_response::Payload::AttestationResponse(AttestationResponse::new()));
        }
        match self.payload {
            ::std::option::Option::Some(rpc_response::Payload::AttestationResponse(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_attestation_response(&mut self) -> AttestationResponse {
        if self.has_attestation_response() {
            match self.payload.take() {
                ::std::option::Option::Some(rpc_response::Payload::AttestationResponse(v)) => v,
                _ => panic!(),
            }
        } else {
            AttestationResponse::new()
        }
    }

    // .attestation.VerificationResponse verification_response = 3;

    pub fn verification_response(&self) -> &VerificationResponse {
        match self.payload {
            ::std::option::Option::Some(rpc_response::Payload::VerificationResponse(ref v)) => v,
            _ => <VerificationResponse as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_verification_response(&mut self) {
        self.payload = ::std::option::Option::None;
    }

    pub fn has_verification_response(&self) -> bool {
        match self.payload {
            ::std::option::Option::Some(rpc_response::Payload::VerificationResponse(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_verification_response(&mut self, v: VerificationResponse) {
        self.payload = ::std::option::Option::Some(rpc_response::Payload::VerificationResponse(v))
    }

    // Mutable pointer to the field.
    pub fn mut_verification_response(&mut self) -> &mut VerificationResponse {
        if let ::std::option::Option::Some(rpc_response::Payload::VerificationResponse(_)) = self.payload {
        } else {
            self.payload = ::std::option::Option::Some(rpc_response::Payload::VerificationResponse(VerificationResponse::new()));
        }
        match self.payload {
            ::std::option::Option::Some(rpc_response::Payload::VerificationResponse(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_verification_response(&mut self) -> VerificationResponse {
        if self.has_verification_response() {
            match self.payload.take() {
                ::std::option::Option::Some(rpc_response::Payload::VerificationResponse(v)) => v,
                _ => panic!(),
            }
        } else {
            VerificationResponse::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "method",
            |m: &RpcResponse| { &m.method },
            |m: &mut RpcResponse| { &mut m.method },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, AttestationResponse>(
            "attestation_response",
            RpcResponse::has_attestation_response,
            RpcResponse::attestation_response,
            RpcResponse::mut_attestation_response,
            RpcResponse::set_attestation_response,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, VerificationResponse>(
            "verification_response",
            RpcResponse::has_verification_response,
            RpcResponse::verification_response,
            RpcResponse::mut_verification_response,
            RpcResponse::set_verification_response,
        ));
        oneofs.push(rpc_response::Payload::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RpcResponse>(
            "RpcResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RpcResponse {
    const NAME: &'static str = "RpcResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.method = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.payload = ::std::option::Option::Some(rpc_response::Payload::AttestationResponse(is.read_message()?));
                },
                26 => {
                    self.payload = ::std::option::Option::Some(rpc_response::Payload::VerificationResponse(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.method != ::protobuf::EnumOrUnknown::new(RpcMethod::RPC_METHOD_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(1, self.method.value());
        }
        if let ::std::option::Option::Some(ref v) = self.payload {
            match v {
                &rpc_response::Payload::AttestationResponse(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &rpc_response::Payload::VerificationResponse(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.method != ::protobuf::EnumOrUnknown::new(RpcMethod::RPC_METHOD_UNSPECIFIED) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.method))?;
        }
        if let ::std::option::Option::Some(ref v) = self.payload {
            match v {
                &rpc_response::Payload::AttestationResponse(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
                },
                &rpc_response::Payload::VerificationResponse(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RpcResponse {
        RpcResponse::new()
    }

    fn clear(&mut self) {
        self.method = ::protobuf::EnumOrUnknown::new(RpcMethod::RPC_METHOD_UNSPECIFIED);
        self.payload = ::std::option::Option::None;
        self.payload = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RpcResponse {
        static instance: RpcResponse = RpcResponse {
            method: ::protobuf::EnumOrUnknown::from_i32(0),
            payload: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RpcResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RpcResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RpcResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RpcResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `RpcResponse`
pub mod rpc_response {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:attestation.RpcResponse.payload)
    pub enum Payload {
        // @@protoc_insertion_point(oneof_field:attestation.RpcResponse.attestation_response)
        AttestationResponse(super::AttestationResponse),
        // @@protoc_insertion_point(oneof_field:attestation.RpcResponse.verification_response)
        VerificationResponse(super::VerificationResponse),
    }

    impl ::protobuf::Oneof for Payload {
    }

    impl ::protobuf::OneofFull for Payload {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::RpcResponse as ::protobuf::MessageFull>::descriptor().oneof_by_name("payload").unwrap()).clone()
        }
    }

    impl Payload {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Payload>("payload")
        }
    }
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:attestation.Mode)
pub enum Mode {
    // @@protoc_insertion_point(enum_value:attestation.Mode.MODE_UNSPECIFIED)
    MODE_UNSPECIFIED = 0,
    // @@protoc_insertion_point(enum_value:attestation.Mode.MODE_PASSPORT)
    MODE_PASSPORT = 1,
    // @@protoc_insertion_point(enum_value:attestation.Mode.MODE_BACKGROUND_CHECK)
    MODE_BACKGROUND_CHECK = 2,
    // @@protoc_insertion_point(enum_value:attestation.Mode.MODE_MIX)
    MODE_MIX = 3,
}

impl ::protobuf::Enum for Mode {
    const NAME: &'static str = "Mode";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<Mode> {
        match value {
            0 => ::std::option::Option::Some(Mode::MODE_UNSPECIFIED),
            1 => ::std::option::Option::Some(Mode::MODE_PASSPORT),
            2 => ::std::option::Option::Some(Mode::MODE_BACKGROUND_CHECK),
            3 => ::std::option::Option::Some(Mode::MODE_MIX),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<Mode> {
        match str {
            "MODE_UNSPECIFIED" => ::std::option::Option::Some(Mode::MODE_UNSPECIFIED),
            "MODE_PASSPORT" => ::std::option::Option::Some(Mode::MODE_PASSPORT),
            "MODE_BACKGROUND_CHECK" => ::std::option::Option::Some(Mode::MODE_BACKGROUND_CHECK),
            "MODE_MIX" => ::std::option::Option::Some(Mode::MODE_MIX),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [Mode] = &[
        Mode::MODE_UNSPECIFIED,
        Mode::MODE_PASSPORT,
        Mode::MODE_BACKGROUND_CHECK,
        Mode::MODE_MIX,
    ];
}

impl ::protobuf::EnumFull for Mode {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("Mode").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for Mode {
    fn default() -> Self {
        Mode::MODE_UNSPECIFIED
    }
}

impl Mode {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<Mode>("Mode")
    }
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:attestation.TEE)
pub enum TEE {
    // @@protoc_insertion_point(enum_value:attestation.TEE.TEE_UNSPECIFIED)
    TEE_UNSPECIFIED = 0,
    // @@protoc_insertion_point(enum_value:attestation.TEE.TEE_CCA)
    TEE_CCA = 1,
    // @@protoc_insertion_point(enum_value:attestation.TEE.TEE_TDX)
    TEE_TDX = 2,
}

impl ::protobuf::Enum for TEE {
    const NAME: &'static str = "TEE";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<TEE> {
        match value {
            0 => ::std::option::Option::Some(TEE::TEE_UNSPECIFIED),
            1 => ::std::option::Option::Some(TEE::TEE_CCA),
            2 => ::std::option::Option::Some(TEE::TEE_TDX),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<TEE> {
        match str {
            "TEE_UNSPECIFIED" => ::std::option::Option::Some(TEE::TEE_UNSPECIFIED),
            "TEE_CCA" => ::std::option::Option::Some(TEE::TEE_CCA),
            "TEE_TDX" => ::std::option::Option::Some(TEE::TEE_TDX),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [TEE] = &[
        TEE::TEE_UNSPECIFIED,
        TEE::TEE_CCA,
        TEE::TEE_TDX,
    ];
}

impl ::protobuf::EnumFull for TEE {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("TEE").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for TEE {
    fn default() -> Self {
        TEE::TEE_UNSPECIFIED
    }
}

impl TEE {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<TEE>("TEE")
    }
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:attestation.ErrorCode)
pub enum ErrorCode {
    // @@protoc_insertion_point(enum_value:attestation.ErrorCode.ErrorCode_OK)
    ErrorCode_OK = 0,
    // @@protoc_insertion_point(enum_value:attestation.ErrorCode.ErrorCode_INVALID_ARGUMENT)
    ErrorCode_INVALID_ARGUMENT = 1,
    // @@protoc_insertion_point(enum_value:attestation.ErrorCode.ErrorCode_INTERNAL)
    ErrorCode_INTERNAL = 2,
    // @@protoc_insertion_point(enum_value:attestation.ErrorCode.ErrorCode_UNSUPPORTED_MODE)
    ErrorCode_UNSUPPORTED_MODE = 3,
}

impl ::protobuf::Enum for ErrorCode {
    const NAME: &'static str = "ErrorCode";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<ErrorCode> {
        match value {
            0 => ::std::option::Option::Some(ErrorCode::ErrorCode_OK),
            1 => ::std::option::Option::Some(ErrorCode::ErrorCode_INVALID_ARGUMENT),
            2 => ::std::option::Option::Some(ErrorCode::ErrorCode_INTERNAL),
            3 => ::std::option::Option::Some(ErrorCode::ErrorCode_UNSUPPORTED_MODE),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<ErrorCode> {
        match str {
            "ErrorCode_OK" => ::std::option::Option::Some(ErrorCode::ErrorCode_OK),
            "ErrorCode_INVALID_ARGUMENT" => ::std::option::Option::Some(ErrorCode::ErrorCode_INVALID_ARGUMENT),
            "ErrorCode_INTERNAL" => ::std::option::Option::Some(ErrorCode::ErrorCode_INTERNAL),
            "ErrorCode_UNSUPPORTED_MODE" => ::std::option::Option::Some(ErrorCode::ErrorCode_UNSUPPORTED_MODE),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [ErrorCode] = &[
        ErrorCode::ErrorCode_OK,
        ErrorCode::ErrorCode_INVALID_ARGUMENT,
        ErrorCode::ErrorCode_INTERNAL,
        ErrorCode::ErrorCode_UNSUPPORTED_MODE,
    ];
}

impl ::protobuf::EnumFull for ErrorCode {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("ErrorCode").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for ErrorCode {
    fn default() -> Self {
        ErrorCode::ErrorCode_OK
    }
}

impl ErrorCode {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<ErrorCode>("ErrorCode")
    }
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:attestation.RpcMethod)
pub enum RpcMethod {
    // @@protoc_insertion_point(enum_value:attestation.RpcMethod.RPC_METHOD_UNSPECIFIED)
    RPC_METHOD_UNSPECIFIED = 0,
    // @@protoc_insertion_point(enum_value:attestation.RpcMethod.RPC_METHOD_ATTESTATION_EVALUATE)
    RPC_METHOD_ATTESTATION_EVALUATE = 1,
    // @@protoc_insertion_point(enum_value:attestation.RpcMethod.RPC_METHOD_VERIFICATION_EVALUATE)
    RPC_METHOD_VERIFICATION_EVALUATE = 2,
}

impl ::protobuf::Enum for RpcMethod {
    const NAME: &'static str = "RpcMethod";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<RpcMethod> {
        match value {
            0 => ::std::option::Option::Some(RpcMethod::RPC_METHOD_UNSPECIFIED),
            1 => ::std::option::Option::Some(RpcMethod::RPC_METHOD_ATTESTATION_EVALUATE),
            2 => ::std::option::Option::Some(RpcMethod::RPC_METHOD_VERIFICATION_EVALUATE),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<RpcMethod> {
        match str {
            "RPC_METHOD_UNSPECIFIED" => ::std::option::Option::Some(RpcMethod::RPC_METHOD_UNSPECIFIED),
            "RPC_METHOD_ATTESTATION_EVALUATE" => ::std::option::Option::Some(RpcMethod::RPC_METHOD_ATTESTATION_EVALUATE),
            "RPC_METHOD_VERIFICATION_EVALUATE" => ::std::option::Option::Some(RpcMethod::RPC_METHOD_VERIFICATION_EVALUATE),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [RpcMethod] = &[
        RpcMethod::RPC_METHOD_UNSPECIFIED,
        RpcMethod::RPC_METHOD_ATTESTATION_EVALUATE,
        RpcMethod::RPC_METHOD_VERIFICATION_EVALUATE,
    ];
}

impl ::protobuf::EnumFull for RpcMethod {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("RpcMethod").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for RpcMethod {
    fn default() -> Self {
        RpcMethod::RPC_METHOD_UNSPECIFIED
    }
}

impl RpcMethod {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<RpcMethod>("RpcMethod")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11attestation.proto\x12\x0battestation\"(\n\x0cHelloRequest\x12\x18\
    \n\x07version\x18\x01\x20\x01(\tR\x07version\"\x91\x01\n\rHelloResponse\
    \x125\n\nerror_code\x18\x01\x20\x01(\x0e2\x16.attestation.ErrorCodeR\ter\
    rorCode\x12\"\n\x03tee\x18\x02\x20\x01(\x0e2\x10.attestation.TEER\x03tee\
    \x12%\n\x04mode\x18\x03\x20\x01(\x0e2\x11.attestation.ModeR\x04mode\"J\n\
    \x08Evidence\x12\x1b\n\tinit_data\x18\x01\x20\x01(\x0cR\x08initData\x12!\
    \n\x0cruntime_data\x18\x02\x20\x01(\x0cR\x0bruntimeData\"A\n\x0cEvidence\
    List\x121\n\x08evidence\x18\x01\x20\x03(\x0b2\x15.attestation.EvidenceR\
    \x08evidence\"Q\n\x12AttestationRequest\x12%\n\x04mode\x18\x01\x20\x01(\
    \x0e2\x11.attestation.ModeR\x04mode\x12\x14\n\x05nonce\x18\x02\x20\x01(\
    \x0cR\x05nonce\"\xc7\x01\n\x13AttestationResponse\x125\n\nerror_code\x18\
    \x01\x20\x01(\x0e2\x16.attestation.ErrorCodeR\terrorCode\x12@\n\revidenc\
    e_list\x18\x02\x20\x01(\x0b2\x19.attestation.EvidenceListH\0R\x0cevidenc\
    eList\x12-\n\x11attestation_token\x18\x03\x20\x01(\x0cH\0R\x10attestatio\
    nTokenB\x08\n\x06result\"H\n\x13VerificationRequest\x121\n\x08evidence\
    \x18\x01\x20\x03(\x0b2\x15.attestation.EvidenceR\x08evidence\"z\n\x14Ver\
    ificationResponse\x125\n\nerror_code\x18\x01\x20\x01(\x0e2\x16.attestati\
    on.ErrorCodeR\terrorCode\x12+\n\x11attestation_token\x18\x02\x20\x01(\
    \x0cR\x10attestationToken\"\x95\x01\n\x14RelyingPartyResponse\x125\n\ner\
    ror_code\x18\x01\x20\x01(\x0e2\x16.attestation.ErrorCodeR\terrorCode\x12\
    0\n\x11attestation_token\x18\x02\x20\x01(\x0cH\0R\x10attestationToken\
    \x88\x01\x01B\x14\n\x12_attestation_token\"\xf2\x01\n\nRpcRequest\x12.\n\
    \x06method\x18\x01\x20\x01(\x0e2\x16.attestation.RpcMethodR\x06method\
    \x12R\n\x13attestation_request\x18\x02\x20\x01(\x0b2\x1f.attestation.Att\
    estationRequestH\0R\x12attestationRequest\x12U\n\x14verification_request\
    \x18\x03\x20\x01(\x0b2\x20.attestation.VerificationRequestH\0R\x13verifi\
    cationRequestB\t\n\x07payload\"\xf9\x01\n\x0bRpcResponse\x12.\n\x06metho\
    d\x18\x01\x20\x01(\x0e2\x16.attestation.RpcMethodR\x06method\x12U\n\x14a\
    ttestation_response\x18\x02\x20\x01(\x0b2\x20.attestation.AttestationRes\
    ponseH\0R\x13attestationResponse\x12X\n\x15verification_response\x18\x03\
    \x20\x01(\x0b2!.attestation.VerificationResponseH\0R\x14verificationResp\
    onseB\t\n\x07payload*X\n\x04Mode\x12\x14\n\x10MODE_UNSPECIFIED\x10\0\x12\
    \x11\n\rMODE_PASSPORT\x10\x01\x12\x19\n\x15MODE_BACKGROUND_CHECK\x10\x02\
    \x12\x0c\n\x08MODE_MIX\x10\x03*4\n\x03TEE\x12\x13\n\x0fTEE_UNSPECIFIED\
    \x10\0\x12\x0b\n\x07TEE_CCA\x10\x01\x12\x0b\n\x07TEE_TDX\x10\x02*u\n\tEr\
    rorCode\x12\x10\n\x0cErrorCode_OK\x10\0\x12\x1e\n\x1aErrorCode_INVALID_A\
    RGUMENT\x10\x01\x12\x16\n\x12ErrorCode_INTERNAL\x10\x02\x12\x1e\n\x1aErr\
    orCode_UNSUPPORTED_MODE\x10\x03*r\n\tRpcMethod\x12\x1a\n\x16RPC_METHOD_U\
    NSPECIFIED\x10\0\x12#\n\x1fRPC_METHOD_ATTESTATION_EVALUATE\x10\x01\x12$\
    \n\x20RPC_METHOD_VERIFICATION_EVALUATE\x10\x022\xcf\x01\n\x12Attestation\
    Service\x12Z\n\x13AttestationEvaluate\x12\x1f.attestation.AttestationReq\
    uest\x1a\x20.attestation.AttestationResponse\"\0\x12]\n\x14VerificationE\
    valuate\x12\x20.attestation.VerificationRequest\x1a!.attestation.Verific\
    ationResponse\"\0b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(11);
            messages.push(HelloRequest::generated_message_descriptor_data());
            messages.push(HelloResponse::generated_message_descriptor_data());
            messages.push(Evidence::generated_message_descriptor_data());
            messages.push(EvidenceList::generated_message_descriptor_data());
            messages.push(AttestationRequest::generated_message_descriptor_data());
            messages.push(AttestationResponse::generated_message_descriptor_data());
            messages.push(VerificationRequest::generated_message_descriptor_data());
            messages.push(VerificationResponse::generated_message_descriptor_data());
            messages.push(RelyingPartyResponse::generated_message_descriptor_data());
            messages.push(RpcRequest::generated_message_descriptor_data());
            messages.push(RpcResponse::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(4);
            enums.push(Mode::generated_enum_descriptor_data());
            enums.push(TEE::generated_enum_descriptor_data());
            enums.push(ErrorCode::generated_enum_descriptor_data());
            enums.push(RpcMethod::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
