addr = "127.0.0.1:50051"
tee = "cca"
verifier_addr = "127.0.0.1:50061"
cca_evidence_path = "test_data/cca/cca-token.cbor"
tdx_evidence_path = "test_data/tdx/tdx_quote_4.dat"
csv_evidence_path = "test_data/csv/csv_evidence.json"
kunpeng_evidence_path = "test_data/kunpeng/kunpeng_evidence.json"
